services:
  naturesbounty-lib-unb-ca:
    build:
      target: development
      context: .
    container_name: naturesbounty-lib-unb-ca
    volumes:
      - ./.nuxt:/nuxt/.nuxt
      - ./app:/nuxt/app
      - ./public:/nuxt/public
      - ./nuxt.config.ts:/nuxt/nuxt.config.ts
      - ./package.json:/nuxt/package.json
      - ./pnpm-lock.yaml:/nuxt/pnpm-lock.yaml
    environment:
      NUXT_SITE_URI: ${NUXT_SITE_URI}
      NUXT_PORT: ${NUXT_PORT}
    ports:
      - '3098:3098'
      - '30980:30980'
    networks:
      - naturesbounty.lib.unb.ca

networks:
  naturesbounty.lib.unb.ca:
    name: naturesbounty.lib.unb.ca
