<script setup>
useHead({ title: 'Foreword' })
</script>

<template>
  <main>
    <h1>Foreword</h1>
    <p>Botanical exploration was formerly considered to be a very glamorous pursuit with tremendous prestige and immense practical application. Governments recognized the great potential of plants as sources of medicines, food, and economic benefits and used to fund botanical exploration. Residents of New Brunswick and elsewhere in Canada commonly had a fair working knowledge of our native plants, since plant collection and identification were part of the study curriculum in most elementary schools. Many scientists and scholars, no matter what their main field of study or focus, also used to have good botanical expertise. Unfortunately, botanical knowledge among members of the public has declined. Expertise on field taxonomy of plants is also diminishing, as funding agencies and researchers focus on molecular technology and scientists become more and more highly specialized. Likewise, many plant collections in herbaria are in jeopardy, as academic institutions face budgetary challenges and no longer seem to understand or recognize the historical, cultural, and conservation importance of such collections.</p>
    <p>Dr. C. Mary Young’s meticulous research documenting nearly 400 years of botanical exploration in New Brunswick reminds us that there are many very important lessons to be learned from carefully examining the past and preserving our heritage. Her fascinating book traces the evolution of botanical science in the context of societal change and the joys, hardships, challenges, inspiration, and determination that epitomize the history of botanical collection. As Mary points out, the botanical explorers of New Brunswick had certain qualities in common, notably tireless enthusiasm, intellectual curiosity, and a very strong work ethic.</p>
    <p>Botanical explorers needed these qualities to help deal with many daunting challenges and the paucity of tools available to them. Imagine years of research data and important collections being lost at sea, the lack of access to accurate maps of the province and the high risk of becoming lost while exploring for plants, the inaccessibility of much of the province and the level of physical fitness needed to get to remote areas, and biting insects so prolific as to nearly drive a person mad. Imagine, also, the lack of comprehensive botanical reference books or field guides, the lack of expertise and knowledge on this continent, and that many plant species were new to science and had not yet been named or described. In our current era of nearly instantaneous gratification in communication and information exchange, it’s difficult to imagine that communication was limited to in-person visits and written correspondence, and often took weeks, months, or sometimes years.</p>
    <p>Mary is a masterful storyteller and her lovely prose is so intimately infused with science that the reader is often unaware about how much they are learning. She weaves an intriguing story of ethnobotany, how plants and society have influenced one another over time. The human elements of her story demonstrate how the botanical explorers’ lack of professional training could be overcome by enthusiasm, how changing ideas and concepts sparked new exploration efforts, and how North Americans and New Brunswickers empowered themselves to take over botanical traditions that were once the exclusive domain of Europeans. Mary also describes how the New Brunswick flora has changed over time and how native plant populations have been affected by humans, traces the path of how plants have evolved and migrated into the province, and reveals historical records of when and how species from abroad were introduced here and became invaders.</p>
    <p>Just like the scholars and scientists that she highlights in her book, Mary exemplifies the time-honoured tradition of a scientist and scholar with a broad range of expertise that extends well beyond the discipline that she devoted her career to. Mary’s academic training and career focused on entomology, but she has become a very knowledgeable botanist, both in the field and in the laboratory. Her scientific expertise and her love of botany are clearly evident in her botanical illustrations that accompany this book; these are not only accurate but beautiful.</p>
    <p>In recounting the history of plant exploration and collection in New Brunswick, Mary humbly omits her own contributions. I can’t visit the Connell Memorial Herbarium without thinking of Mary and her devotion to the plant collections there. I picture her lovingly mounting the plant specimens onto herbarium sheets and preparing and affixing labels, carefully scrutinizing specimens to ensure they have been correctly identified, and precisely mapping, cataloguing, and recording the data for each plant collection that she has handled. I picture her excitement at discovering a herbarium specimen of Butterfly Weed (Asclepias tuberosa), collected from the Petitcodiac River in the 1800s, far to the north of its known geographic range. When I’m at Southwest Head on Grand Manan, I can envision Mary admiring the diminutive Tiny All-seed (Radiola linoides) that grows there. And whenever I’m at one of the Nature Trust of New Brunswick’s nature preserves, I think of how Mary’s leadership helped inspire the protection of important natural areas and their plant residents in this province. Mary is a perfect role model for carrying out the wishes of our friend, the late Hal Hinds, who encouraged readers of his Flora of New Brunswick to “Learn them, love them, protect them.”</p>
    <p>It is my sincere hope that Mary’s stimulating book will rekindle a sense of wonder and pride regarding New Brunswick’s rich botanical legacy, and will inspire current and future generations to continue the fine tradition of botanical exploration in this province, as well as to foster greater commitment to stewardship and conservation. Let us also hope that Mary’s astute observation that great diversity of forms exist within plant species in New Brunswick becomes more widely recognized by scientists, researchers, and funding agencies, so her dream for the complexity of their genetic make-up and their relationships with the environment to be adequately studied will be realized.</p>
    <p>
      Dr. James Goltz<br>
      Fredericton, New Brunswick<br>
      2014
    </p>
  </main>
</template>
