favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost:3098/themes/contrib/unb_lib_theme/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  unb_lib_theme: 8000
  naturesbounty_lib_unb_ca: 8000
